#define CHICKPEA_SYSTEM_IMPLEMENTATION
#include <chkp_system.h>
#define CHICKPEA_DRAW_IMPLEMENTATION
#include <chkp_draw.h>
#define CHICKPEA_MATRIX_IMPLEMENTATION
#include <chkp_matrix.h>
#define CHICKPEA_UTIL_IMPLEMENTATION
#include <chkp_util.h>
#define CHICKPEA_SHADER_IMPLEMENTATION
#include <chkp_shader.h>
